postgres:
  user: ""
  pass: ""
  db: "sampledb"

expenseService:
  replicaCount: 1
<<<<<<< HEAD:multicontainer-helm/solutions/expense-service/values.yaml
  image: "registry.ocp4.example.com:8443/redhattraining/ocpdev-expense-service:4.12"
=======
  image: "registry.ocp4.example.com:8443/redhattraining/ocpdev-expense-service:4.18"
>>>>>>> cc8cc5c57f891eaaee6310ddb6028980fe98a446:solutions/multicontainer-helm/expense-service/values.yaml
  host: "expense-service"
  domain: "apps.ocp4.example.com"
